In [396]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [397]:
digits=load_digits()

In [398]:
x=digits.data
y=digits.target

In [399]:
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler().fit_transform(x)

In [400]:
from sklearn.model_selection import train_test_split

In [401]:
from sklearn.decomposition import PCA

In [650]:
pca=PCA(n_components=15)

In [651]:
x_new=pca.fit_transform(x)
x_new

array([[ -1.25946486,  21.27487652,  -9.46305309, ...,   0.85520251,
         -3.35778145,   5.91479085],
       [  7.9576256 , -20.76870171,   4.43948524, ...,  -2.51333262,
         -6.48195299,  -2.28747578],
       [  6.99193352,  -9.95598   ,   2.95855223, ...,   0.26495764,
          6.85504831,  -1.79120799],
       ...,
       [ 10.80126276,  -6.96024098,   5.59958047, ...,   3.40289259,
          1.27538899,   2.63004111],
       [ -4.87207926,  12.42395368, -10.170891  , ...,  -9.30627976,
         -1.22608767,  10.71492791],
       [ -0.34440035,   6.36556361,  10.77372325, ...,   4.65873526,
          7.08587206,   0.73587013]])

In [652]:
from sklearn.linear_model import LogisticRegression

In [653]:
X_train, X_test, Y_train, Y_test = train_test_split(x_new , y, test_size=0.20,random_state=20)

In [654]:
reg = LogisticRegression()

In [655]:
reg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [656]:
pred = reg.predict(X_test)

In [657]:
from sklearn.metrics import *

In [658]:
accuracy_score(pred, Y_test)

0.9611111111111111

In [659]:
print(confusion_matrix(pred, Y_test))

[[37  0  0  0  0  1  0  0  0  0]
 [ 0 30  0  0  0  0  3  0  0  1]
 [ 0  0 28  0  0  0  0  0  0  0]
 [ 0  1  0 36  0  0  0  0  0  0]
 [ 0  0  0  0 39  0  0  0  0  0]
 [ 0  0  0  0  0 32  0  0  0  1]
 [ 0  0  0  0  0  0 42  0  1  0]
 [ 0  0  0  2  0  0  0 40  1  0]
 [ 0  0  0  0  1  0  0  0 33  1]
 [ 0  0  0  0  1  0  0  0  0 29]]


In [660]:
print(classification_report(pred, Y_test))

             precision    recall  f1-score   support

          0       1.00      0.97      0.99        38
          1       0.97      0.88      0.92        34
          2       1.00      1.00      1.00        28
          3       0.95      0.97      0.96        37
          4       0.95      1.00      0.97        39
          5       0.97      0.97      0.97        33
          6       0.93      0.98      0.95        43
          7       1.00      0.93      0.96        43
          8       0.94      0.94      0.94        35
          9       0.91      0.97      0.94        30

avg / total       0.96      0.96      0.96       360

