In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import *
from sklearn.datasets import load_digits
import matplotlib.pyplot as mlt
%matplotlib inline

In [3]:
digit= load_digits()
x= digit.data
y= digit.target

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.3)

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
reg = LogisticRegression()
reg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
pred = reg.predict(X_test)

In [11]:
reg.score(X_test,Y_test)*100

95.55555555555556

In [13]:
from sklearn import model_selection

In [14]:
kfold=model_selection.KFold(n_splits=10,random_state = 7)

In [16]:
result= model_selection.cross_val_score(reg,x,y,cv=kfold,scoring='accuracy')

In [17]:
result

array([0.90555556, 0.95      , 0.89444444, 0.91666667, 0.94444444,
       0.97222222, 0.97777778, 0.95530726, 0.8603352 , 0.93854749])

In [18]:
result.sum()/10

0.931530105524519

In [20]:
result= model_selection.cross_val_score(reg,x,y,cv=kfold,scoring='neg_log_loss')

In [21]:
result

array([-0.45788103, -0.14423066, -0.61750718, -0.27275699, -0.27594926,
       -0.12823227, -0.11029206, -0.12335128, -0.62646858, -0.68574502])

In [22]:
result.sum()/10

-0.34424143158838305

In [26]:
result= model_selection.cross_val_score(reg,x,y,cv=kfold,scoring='r2')

In [27]:
result

array([0.73184699, 0.86942354, 0.81023661, 0.79423609, 0.82434177,
       0.94343263, 0.92524112, 0.90725247, 0.60169024, 0.82555495])

In [28]:
result.sum()/10

0.8233256404108781

In [29]:
from sklearn.metrics import mean_absolute_error

In [35]:
mean_absolute_error(Y_test, pred)

0.17222222222222222

In [36]:
from sklearn.metrics import mean_squared_error

In [37]:
mean_squared_error(Y_test, pred)

0.8759259259259259

In [42]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test,pred))

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  1  0  0  1]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 45  0  3  0  0  2  0]
 [ 0  2  0  0 53  0  0  0  0  0]
 [ 0  0  0  0  0 63  0  0  1  1]
 [ 0  1  0  0  0  0 57  0  0  0]
 [ 0  0  0  0  0  0  0 43  1  1]
 [ 0  3  0  0  1  1  0  0 60  1]
 [ 0  1  0  0  0  0  0  3  0 42]]


In [39]:
from sklearn.metrics import accuracy_score

In [40]:
print('Accuracy Score :',accuracy_score(Y_test,pred))

Accuracy Score : 0.9555555555555556
Report : 
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        63
          1       0.88      0.96      0.92        54
          2       1.00      1.00      1.00        38
          3       1.00      0.90      0.95        50
          4       0.98      0.96      0.97        55
          5       0.94      0.97      0.95        65
          6       0.98      0.98      0.98        58
          7       0.93      0.96      0.95        45
          8       0.94      0.91      0.92        66
          9       0.91      0.91      0.91        46

avg / total       0.96      0.96      0.96       540



In [43]:
from sklearn.metrics import classification_report

print('Report : ')

print(classification_report(Y_test, pred))

Report : 
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        63
          1       0.88      0.96      0.92        54
          2       1.00      1.00      1.00        38
          3       1.00      0.90      0.95        50
          4       0.98      0.96      0.97        55
          5       0.94      0.97      0.95        65
          6       0.98      0.98      0.98        58
          7       0.93      0.96      0.95        45
          8       0.94      0.91      0.92        66
          9       0.91      0.91      0.91        46

avg / total       0.96      0.96      0.96       540

